# dist: trusty

language: python

python: "3.7"

cache: pip

install: "pip install sphinx"

script:
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build/html
  on:
    branch: master
  target-branch: gh-pages

